# Generated by Django 4.2.1 on 2023-05-24 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nudge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='nudge_images/')),
                ('scheduled_on', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=255)),
                ('invitation', models.CharField(max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
